apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-nodb
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.appNodb.replicas }}
  selector:
    matchLabels:
      app: app-nodb
  template:
    metadata:
      labels:
        app: app-nodb
    spec: 
      containers:
      - name: app-nodb-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["python"]
        args: ["app_nodb.py"]
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: {{ .Values.appNodb.resources.requests.cpu }}
            memory: {{ .Values.appNodb.resources.requests.memory }}
          limits:
            cpu: {{ .Values.appNodb.resources.limits.cpu }}
            memory: {{ .Values.appNodb.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appNodb.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: app-nodb
  ports:
    - port: {{ .Values.appNodb.service.port }}
      targetPort: {{ .Values.appNodb.service.targetPort }}
